name: Code Style

on: [push, pull_request]
permissions:
  contents: read
jobs:
  fpm:
    name: Fortran Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: Install fprettify
        run: |
          sudo apt-get install -y python3-pip
          pip3 install fprettify
      - name: Format Fortran files
        run: |
          fprettify -i 4 -d --recursive .
          # Check if files were modified and stage them for commit
          git diff --exit-code
          if [ $? -ne 0 ]; then
              echo "Files were modified by fprettify, adding changes."
              git add .
          else
              echo "No files were modified."
          fi
      - name: Fail if needs reformatting
        run: |
          # Check if there are uncommitted changes
          if [[ $(git status --porcelain) ]]; then
             echo "please reformat/fprettify these files:"
             git status --porcelain=v1
             echo "exact diff:"
             
             # Show the formatting changes with fprettify
             fprettify -i 4 -d --recursive .  # This will display debug output

             # Display the git diff
             git diff
             exit 1
          else
             echo "All files are properly formatted."
          fi     
