name: Code Style

on: [push, pull_request]
permissions:
  contents: read
jobs:
  fpm:
    name: Fortran Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: Install fprettify
        run: |
          sudo apt-get install -y python3-pip
          pip3 install fprettify
      - name: Format Fortran files
        id: format
        run: |
          # Run fprettify and capture output
          output=$(fprettify -i 4 --recursive .)
          echo "$output"
          # Check if there were any changes
          if [[ $(git status --porcelain) ]]; then
            echo "Files were modified:"
            echo "$output"
            git diff
            exit 1
          else
            echo "All files are properly formatted."
          fi                   
