name: Code Style

on: [push, pull_request]
permissions:
  contents: read
jobs:
  fpm:
    name: Fortran Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: Install fprettify
        run: |
          sudo apt-get install -y python3-pip
          pip3 install fprettify
      - name: Format Fortran files
        run: |
          fprettify -i 4 -d --recursive . 2>&1
          git add .
      - name: Fail if needs reformatting
        run: |                  
             echo "please reformat/fprettify these files:"
             git status --porcelain=v1
             echo "exact diff:"
                          
             fprettify -i 4 -d --recursive .              
             git diff
             exit 1                       
